services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./mirror/mirror:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  apt-mirror:
    build: ./apt-mirror
    restart: unless-stopped
    environment:
      - CRON_SCHEDULE=0 2 * * *
    volumes:
      - ./mirror:/var/spool/apt-mirror
